# Generated by Django 4.2.7 on 2024-02-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзины', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
