# Generated by Django 4.2.7 on 2024-01-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_product_discount_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
